name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: php install
      run: cd /var/www/html/actions-runner && git pull && composer install - no-dev && php artisan migrate - force && php artisan optimize
    - name: change permission
      run: sudo chmod -R 777 /var/www/html/
      
